/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StaffRouteImport } from './routes/_staff'
import { Route as EntityRouteImport } from './routes/_entity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffDashboardRouteImport } from './routes/_staff.dashboard'
import { Route as EntityPortalRouteImport } from './routes/_entity.portal'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/_staff',
  getParentRoute: () => rootRouteImport,
} as any)
const EntityRoute = EntityRouteImport.update({
  id: '/_entity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StaffRoute,
} as any)
const EntityPortalRoute = EntityPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => EntityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof EntityPortalRoute
  '/dashboard': typeof StaffDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof EntityPortalRoute
  '/dashboard': typeof StaffDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_entity': typeof EntityRouteWithChildren
  '/_staff': typeof StaffRouteWithChildren
  '/login': typeof LoginRoute
  '/_entity/portal': typeof EntityPortalRoute
  '/_staff/dashboard': typeof StaffDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/portal' | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/portal' | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_entity'
    | '/_staff'
    | '/login'
    | '/_entity/portal'
    | '/_staff/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntityRoute: typeof EntityRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff': {
      id: '/_staff'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_entity': {
      id: '/_entity'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof EntityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff/dashboard': {
      id: '/_staff/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_entity/portal': {
      id: '/_entity/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof EntityPortalRouteImport
      parentRoute: typeof EntityRoute
    }
  }
}

interface EntityRouteChildren {
  EntityPortalRoute: typeof EntityPortalRoute
}

const EntityRouteChildren: EntityRouteChildren = {
  EntityPortalRoute: EntityPortalRoute,
}

const EntityRouteWithChildren =
  EntityRoute._addFileChildren(EntityRouteChildren)

interface StaffRouteChildren {
  StaffDashboardRoute: typeof StaffDashboardRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffDashboardRoute: StaffDashboardRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntityRoute: EntityRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
