/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StaffRouteImport } from './routes/_staff'
import { Route as EntityRouteImport } from './routes/_entity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as StaffSettingsRouteImport } from './routes/_staff.settings'
import { Route as StaffMessagesRouteImport } from './routes/_staff.messages'
import { Route as StaffDashboardRouteImport } from './routes/_staff.dashboard'
import { Route as StaffContentRouteImport } from './routes/_staff.content'
import { Route as StaffAttendanceRouteImport } from './routes/_staff.attendance'
import { Route as StaffParticipantsIndexRouteImport } from './routes/_staff.participants.index'
import { Route as StaffContentIndexRouteImport } from './routes/_staff.content.index'
import { Route as EntityPortalIndexRouteImport } from './routes/_entity.portal.index'
import { Route as StaffParticipantsNewRouteImport } from './routes/_staff.participants.new'
import { Route as StaffParticipantsInvitesRouteImport } from './routes/_staff.participants.invites'
import { Route as StaffParticipantsDeletionRequestsRouteImport } from './routes/_staff.participants.deletion-requests'
import { Route as StaffParticipantsParticipantIdRouteImport } from './routes/_staff.participants.$participantId'
import { Route as EntityPortalServicesRouteImport } from './routes/_entity.portal.services'
import { Route as EntityPortalReferralsRouteImport } from './routes/_entity.portal.referrals'
import { Route as EntityPortalMessagesRouteImport } from './routes/_entity.portal.messages'
import { Route as EntityPortalEventsRouteImport } from './routes/_entity.portal.events'
import { Route as StaffContentEventsIndexRouteImport } from './routes/_staff.content.events.index'
import { Route as StaffContentAnnouncementsIndexRouteImport } from './routes/_staff.content.announcements.index'
import { Route as StaffContentEventsNewRouteImport } from './routes/_staff.content.events.new'
import { Route as StaffContentEventsCategoriesRouteImport } from './routes/_staff.content.events.categories'
import { Route as StaffContentEventsEventIdRouteImport } from './routes/_staff.content.events.$eventId'
import { Route as StaffContentAnnouncementsNewRouteImport } from './routes/_staff.content.announcements.new'
import { Route as StaffContentAnnouncementsAnnouncementIdRouteImport } from './routes/_staff.content.announcements.$announcementId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/_staff',
  getParentRoute: () => rootRouteImport,
} as any)
const EntityRoute = EntityRouteImport.update({
  id: '/_entity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSettingsRoute = StaffSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StaffRoute,
} as any)
const StaffMessagesRoute = StaffMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => StaffRoute,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StaffRoute,
} as any)
const StaffContentRoute = StaffContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAttendanceRoute = StaffAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StaffRoute,
} as any)
const StaffParticipantsIndexRoute = StaffParticipantsIndexRouteImport.update({
  id: '/participants/',
  path: '/participants/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffContentIndexRoute = StaffContentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffContentRoute,
} as any)
const EntityPortalIndexRoute = EntityPortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => EntityRoute,
} as any)
const StaffParticipantsNewRoute = StaffParticipantsNewRouteImport.update({
  id: '/participants/new',
  path: '/participants/new',
  getParentRoute: () => StaffRoute,
} as any)
const StaffParticipantsInvitesRoute =
  StaffParticipantsInvitesRouteImport.update({
    id: '/participants/invites',
    path: '/participants/invites',
    getParentRoute: () => StaffRoute,
  } as any)
const StaffParticipantsDeletionRequestsRoute =
  StaffParticipantsDeletionRequestsRouteImport.update({
    id: '/participants/deletion-requests',
    path: '/participants/deletion-requests',
    getParentRoute: () => StaffRoute,
  } as any)
const StaffParticipantsParticipantIdRoute =
  StaffParticipantsParticipantIdRouteImport.update({
    id: '/participants/$participantId',
    path: '/participants/$participantId',
    getParentRoute: () => StaffRoute,
  } as any)
const EntityPortalServicesRoute = EntityPortalServicesRouteImport.update({
  id: '/portal/services',
  path: '/portal/services',
  getParentRoute: () => EntityRoute,
} as any)
const EntityPortalReferralsRoute = EntityPortalReferralsRouteImport.update({
  id: '/portal/referrals',
  path: '/portal/referrals',
  getParentRoute: () => EntityRoute,
} as any)
const EntityPortalMessagesRoute = EntityPortalMessagesRouteImport.update({
  id: '/portal/messages',
  path: '/portal/messages',
  getParentRoute: () => EntityRoute,
} as any)
const EntityPortalEventsRoute = EntityPortalEventsRouteImport.update({
  id: '/portal/events',
  path: '/portal/events',
  getParentRoute: () => EntityRoute,
} as any)
const StaffContentEventsIndexRoute = StaffContentEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => StaffContentRoute,
} as any)
const StaffContentAnnouncementsIndexRoute =
  StaffContentAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => StaffContentRoute,
  } as any)
const StaffContentEventsNewRoute = StaffContentEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => StaffContentRoute,
} as any)
const StaffContentEventsCategoriesRoute =
  StaffContentEventsCategoriesRouteImport.update({
    id: '/events/categories',
    path: '/events/categories',
    getParentRoute: () => StaffContentRoute,
  } as any)
const StaffContentEventsEventIdRoute =
  StaffContentEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => StaffContentRoute,
  } as any)
const StaffContentAnnouncementsNewRoute =
  StaffContentAnnouncementsNewRouteImport.update({
    id: '/announcements/new',
    path: '/announcements/new',
    getParentRoute: () => StaffContentRoute,
  } as any)
const StaffContentAnnouncementsAnnouncementIdRoute =
  StaffContentAnnouncementsAnnouncementIdRouteImport.update({
    id: '/announcements/$announcementId',
    path: '/announcements/$announcementId',
    getParentRoute: () => StaffContentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/attendance': typeof StaffAttendanceRoute
  '/content': typeof StaffContentRouteWithChildren
  '/dashboard': typeof StaffDashboardRoute
  '/messages': typeof StaffMessagesRoute
  '/settings': typeof StaffSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/portal/events': typeof EntityPortalEventsRoute
  '/portal/messages': typeof EntityPortalMessagesRoute
  '/portal/referrals': typeof EntityPortalReferralsRoute
  '/portal/services': typeof EntityPortalServicesRoute
  '/participants/$participantId': typeof StaffParticipantsParticipantIdRoute
  '/participants/deletion-requests': typeof StaffParticipantsDeletionRequestsRoute
  '/participants/invites': typeof StaffParticipantsInvitesRoute
  '/participants/new': typeof StaffParticipantsNewRoute
  '/portal/': typeof EntityPortalIndexRoute
  '/content/': typeof StaffContentIndexRoute
  '/participants/': typeof StaffParticipantsIndexRoute
  '/content/announcements/$announcementId': typeof StaffContentAnnouncementsAnnouncementIdRoute
  '/content/announcements/new': typeof StaffContentAnnouncementsNewRoute
  '/content/events/$eventId': typeof StaffContentEventsEventIdRoute
  '/content/events/categories': typeof StaffContentEventsCategoriesRoute
  '/content/events/new': typeof StaffContentEventsNewRoute
  '/content/announcements/': typeof StaffContentAnnouncementsIndexRoute
  '/content/events/': typeof StaffContentEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/attendance': typeof StaffAttendanceRoute
  '/dashboard': typeof StaffDashboardRoute
  '/messages': typeof StaffMessagesRoute
  '/settings': typeof StaffSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/portal/events': typeof EntityPortalEventsRoute
  '/portal/messages': typeof EntityPortalMessagesRoute
  '/portal/referrals': typeof EntityPortalReferralsRoute
  '/portal/services': typeof EntityPortalServicesRoute
  '/participants/$participantId': typeof StaffParticipantsParticipantIdRoute
  '/participants/deletion-requests': typeof StaffParticipantsDeletionRequestsRoute
  '/participants/invites': typeof StaffParticipantsInvitesRoute
  '/participants/new': typeof StaffParticipantsNewRoute
  '/portal': typeof EntityPortalIndexRoute
  '/content': typeof StaffContentIndexRoute
  '/participants': typeof StaffParticipantsIndexRoute
  '/content/announcements/$announcementId': typeof StaffContentAnnouncementsAnnouncementIdRoute
  '/content/announcements/new': typeof StaffContentAnnouncementsNewRoute
  '/content/events/$eventId': typeof StaffContentEventsEventIdRoute
  '/content/events/categories': typeof StaffContentEventsCategoriesRoute
  '/content/events/new': typeof StaffContentEventsNewRoute
  '/content/announcements': typeof StaffContentAnnouncementsIndexRoute
  '/content/events': typeof StaffContentEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_entity': typeof EntityRouteWithChildren
  '/_staff': typeof StaffRouteWithChildren
  '/login': typeof LoginRoute
  '/_staff/attendance': typeof StaffAttendanceRoute
  '/_staff/content': typeof StaffContentRouteWithChildren
  '/_staff/dashboard': typeof StaffDashboardRoute
  '/_staff/messages': typeof StaffMessagesRoute
  '/_staff/settings': typeof StaffSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_entity/portal/events': typeof EntityPortalEventsRoute
  '/_entity/portal/messages': typeof EntityPortalMessagesRoute
  '/_entity/portal/referrals': typeof EntityPortalReferralsRoute
  '/_entity/portal/services': typeof EntityPortalServicesRoute
  '/_staff/participants/$participantId': typeof StaffParticipantsParticipantIdRoute
  '/_staff/participants/deletion-requests': typeof StaffParticipantsDeletionRequestsRoute
  '/_staff/participants/invites': typeof StaffParticipantsInvitesRoute
  '/_staff/participants/new': typeof StaffParticipantsNewRoute
  '/_entity/portal/': typeof EntityPortalIndexRoute
  '/_staff/content/': typeof StaffContentIndexRoute
  '/_staff/participants/': typeof StaffParticipantsIndexRoute
  '/_staff/content/announcements/$announcementId': typeof StaffContentAnnouncementsAnnouncementIdRoute
  '/_staff/content/announcements/new': typeof StaffContentAnnouncementsNewRoute
  '/_staff/content/events/$eventId': typeof StaffContentEventsEventIdRoute
  '/_staff/content/events/categories': typeof StaffContentEventsCategoriesRoute
  '/_staff/content/events/new': typeof StaffContentEventsNewRoute
  '/_staff/content/announcements/': typeof StaffContentAnnouncementsIndexRoute
  '/_staff/content/events/': typeof StaffContentEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/attendance'
    | '/content'
    | '/dashboard'
    | '/messages'
    | '/settings'
    | '/auth/callback'
    | '/portal/events'
    | '/portal/messages'
    | '/portal/referrals'
    | '/portal/services'
    | '/participants/$participantId'
    | '/participants/deletion-requests'
    | '/participants/invites'
    | '/participants/new'
    | '/portal/'
    | '/content/'
    | '/participants/'
    | '/content/announcements/$announcementId'
    | '/content/announcements/new'
    | '/content/events/$eventId'
    | '/content/events/categories'
    | '/content/events/new'
    | '/content/announcements/'
    | '/content/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/attendance'
    | '/dashboard'
    | '/messages'
    | '/settings'
    | '/auth/callback'
    | '/portal/events'
    | '/portal/messages'
    | '/portal/referrals'
    | '/portal/services'
    | '/participants/$participantId'
    | '/participants/deletion-requests'
    | '/participants/invites'
    | '/participants/new'
    | '/portal'
    | '/content'
    | '/participants'
    | '/content/announcements/$announcementId'
    | '/content/announcements/new'
    | '/content/events/$eventId'
    | '/content/events/categories'
    | '/content/events/new'
    | '/content/announcements'
    | '/content/events'
  id:
    | '__root__'
    | '/'
    | '/_entity'
    | '/_staff'
    | '/login'
    | '/_staff/attendance'
    | '/_staff/content'
    | '/_staff/dashboard'
    | '/_staff/messages'
    | '/_staff/settings'
    | '/auth/callback'
    | '/_entity/portal/events'
    | '/_entity/portal/messages'
    | '/_entity/portal/referrals'
    | '/_entity/portal/services'
    | '/_staff/participants/$participantId'
    | '/_staff/participants/deletion-requests'
    | '/_staff/participants/invites'
    | '/_staff/participants/new'
    | '/_entity/portal/'
    | '/_staff/content/'
    | '/_staff/participants/'
    | '/_staff/content/announcements/$announcementId'
    | '/_staff/content/announcements/new'
    | '/_staff/content/events/$eventId'
    | '/_staff/content/events/categories'
    | '/_staff/content/events/new'
    | '/_staff/content/announcements/'
    | '/_staff/content/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntityRoute: typeof EntityRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff': {
      id: '/_staff'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_entity': {
      id: '/_entity'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof EntityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff/settings': {
      id: '/_staff/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof StaffSettingsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/messages': {
      id: '/_staff/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof StaffMessagesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/dashboard': {
      id: '/_staff/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/content': {
      id: '/_staff/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof StaffContentRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/attendance': {
      id: '/_staff/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof StaffAttendanceRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/participants/': {
      id: '/_staff/participants/'
      path: '/participants'
      fullPath: '/participants/'
      preLoaderRoute: typeof StaffParticipantsIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/content/': {
      id: '/_staff/content/'
      path: '/'
      fullPath: '/content/'
      preLoaderRoute: typeof StaffContentIndexRouteImport
      parentRoute: typeof StaffContentRoute
    }
    '/_entity/portal/': {
      id: '/_entity/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof EntityPortalIndexRouteImport
      parentRoute: typeof EntityRoute
    }
    '/_staff/participants/new': {
      id: '/_staff/participants/new'
      path: '/participants/new'
      fullPath: '/participants/new'
      preLoaderRoute: typeof StaffParticipantsNewRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/participants/invites': {
      id: '/_staff/participants/invites'
      path: '/participants/invites'
      fullPath: '/participants/invites'
      preLoaderRoute: typeof StaffParticipantsInvitesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/participants/deletion-requests': {
      id: '/_staff/participants/deletion-requests'
      path: '/participants/deletion-requests'
      fullPath: '/participants/deletion-requests'
      preLoaderRoute: typeof StaffParticipantsDeletionRequestsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/participants/$participantId': {
      id: '/_staff/participants/$participantId'
      path: '/participants/$participantId'
      fullPath: '/participants/$participantId'
      preLoaderRoute: typeof StaffParticipantsParticipantIdRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_entity/portal/services': {
      id: '/_entity/portal/services'
      path: '/portal/services'
      fullPath: '/portal/services'
      preLoaderRoute: typeof EntityPortalServicesRouteImport
      parentRoute: typeof EntityRoute
    }
    '/_entity/portal/referrals': {
      id: '/_entity/portal/referrals'
      path: '/portal/referrals'
      fullPath: '/portal/referrals'
      preLoaderRoute: typeof EntityPortalReferralsRouteImport
      parentRoute: typeof EntityRoute
    }
    '/_entity/portal/messages': {
      id: '/_entity/portal/messages'
      path: '/portal/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof EntityPortalMessagesRouteImport
      parentRoute: typeof EntityRoute
    }
    '/_entity/portal/events': {
      id: '/_entity/portal/events'
      path: '/portal/events'
      fullPath: '/portal/events'
      preLoaderRoute: typeof EntityPortalEventsRouteImport
      parentRoute: typeof EntityRoute
    }
    '/_staff/content/events/': {
      id: '/_staff/content/events/'
      path: '/events'
      fullPath: '/content/events/'
      preLoaderRoute: typeof StaffContentEventsIndexRouteImport
      parentRoute: typeof StaffContentRoute
    }
    '/_staff/content/announcements/': {
      id: '/_staff/content/announcements/'
      path: '/announcements'
      fullPath: '/content/announcements/'
      preLoaderRoute: typeof StaffContentAnnouncementsIndexRouteImport
      parentRoute: typeof StaffContentRoute
    }
    '/_staff/content/events/new': {
      id: '/_staff/content/events/new'
      path: '/events/new'
      fullPath: '/content/events/new'
      preLoaderRoute: typeof StaffContentEventsNewRouteImport
      parentRoute: typeof StaffContentRoute
    }
    '/_staff/content/events/categories': {
      id: '/_staff/content/events/categories'
      path: '/events/categories'
      fullPath: '/content/events/categories'
      preLoaderRoute: typeof StaffContentEventsCategoriesRouteImport
      parentRoute: typeof StaffContentRoute
    }
    '/_staff/content/events/$eventId': {
      id: '/_staff/content/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/content/events/$eventId'
      preLoaderRoute: typeof StaffContentEventsEventIdRouteImport
      parentRoute: typeof StaffContentRoute
    }
    '/_staff/content/announcements/new': {
      id: '/_staff/content/announcements/new'
      path: '/announcements/new'
      fullPath: '/content/announcements/new'
      preLoaderRoute: typeof StaffContentAnnouncementsNewRouteImport
      parentRoute: typeof StaffContentRoute
    }
    '/_staff/content/announcements/$announcementId': {
      id: '/_staff/content/announcements/$announcementId'
      path: '/announcements/$announcementId'
      fullPath: '/content/announcements/$announcementId'
      preLoaderRoute: typeof StaffContentAnnouncementsAnnouncementIdRouteImport
      parentRoute: typeof StaffContentRoute
    }
  }
}

interface EntityRouteChildren {
  EntityPortalEventsRoute: typeof EntityPortalEventsRoute
  EntityPortalMessagesRoute: typeof EntityPortalMessagesRoute
  EntityPortalReferralsRoute: typeof EntityPortalReferralsRoute
  EntityPortalServicesRoute: typeof EntityPortalServicesRoute
  EntityPortalIndexRoute: typeof EntityPortalIndexRoute
}

const EntityRouteChildren: EntityRouteChildren = {
  EntityPortalEventsRoute: EntityPortalEventsRoute,
  EntityPortalMessagesRoute: EntityPortalMessagesRoute,
  EntityPortalReferralsRoute: EntityPortalReferralsRoute,
  EntityPortalServicesRoute: EntityPortalServicesRoute,
  EntityPortalIndexRoute: EntityPortalIndexRoute,
}

const EntityRouteWithChildren =
  EntityRoute._addFileChildren(EntityRouteChildren)

interface StaffContentRouteChildren {
  StaffContentIndexRoute: typeof StaffContentIndexRoute
  StaffContentAnnouncementsAnnouncementIdRoute: typeof StaffContentAnnouncementsAnnouncementIdRoute
  StaffContentAnnouncementsNewRoute: typeof StaffContentAnnouncementsNewRoute
  StaffContentEventsEventIdRoute: typeof StaffContentEventsEventIdRoute
  StaffContentEventsCategoriesRoute: typeof StaffContentEventsCategoriesRoute
  StaffContentEventsNewRoute: typeof StaffContentEventsNewRoute
  StaffContentAnnouncementsIndexRoute: typeof StaffContentAnnouncementsIndexRoute
  StaffContentEventsIndexRoute: typeof StaffContentEventsIndexRoute
}

const StaffContentRouteChildren: StaffContentRouteChildren = {
  StaffContentIndexRoute: StaffContentIndexRoute,
  StaffContentAnnouncementsAnnouncementIdRoute:
    StaffContentAnnouncementsAnnouncementIdRoute,
  StaffContentAnnouncementsNewRoute: StaffContentAnnouncementsNewRoute,
  StaffContentEventsEventIdRoute: StaffContentEventsEventIdRoute,
  StaffContentEventsCategoriesRoute: StaffContentEventsCategoriesRoute,
  StaffContentEventsNewRoute: StaffContentEventsNewRoute,
  StaffContentAnnouncementsIndexRoute: StaffContentAnnouncementsIndexRoute,
  StaffContentEventsIndexRoute: StaffContentEventsIndexRoute,
}

const StaffContentRouteWithChildren = StaffContentRoute._addFileChildren(
  StaffContentRouteChildren,
)

interface StaffRouteChildren {
  StaffAttendanceRoute: typeof StaffAttendanceRoute
  StaffContentRoute: typeof StaffContentRouteWithChildren
  StaffDashboardRoute: typeof StaffDashboardRoute
  StaffMessagesRoute: typeof StaffMessagesRoute
  StaffSettingsRoute: typeof StaffSettingsRoute
  StaffParticipantsParticipantIdRoute: typeof StaffParticipantsParticipantIdRoute
  StaffParticipantsDeletionRequestsRoute: typeof StaffParticipantsDeletionRequestsRoute
  StaffParticipantsInvitesRoute: typeof StaffParticipantsInvitesRoute
  StaffParticipantsNewRoute: typeof StaffParticipantsNewRoute
  StaffParticipantsIndexRoute: typeof StaffParticipantsIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffAttendanceRoute: StaffAttendanceRoute,
  StaffContentRoute: StaffContentRouteWithChildren,
  StaffDashboardRoute: StaffDashboardRoute,
  StaffMessagesRoute: StaffMessagesRoute,
  StaffSettingsRoute: StaffSettingsRoute,
  StaffParticipantsParticipantIdRoute: StaffParticipantsParticipantIdRoute,
  StaffParticipantsDeletionRequestsRoute:
    StaffParticipantsDeletionRequestsRoute,
  StaffParticipantsInvitesRoute: StaffParticipantsInvitesRoute,
  StaffParticipantsNewRoute: StaffParticipantsNewRoute,
  StaffParticipantsIndexRoute: StaffParticipantsIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntityRoute: EntityRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
