export default {
  extends: ['@commitlint/config-conventional'],
  plugins: [
    {
      rules: {
        'subject-rapp-id': ({ header }) => [
          /\(RAPP-\d+\)$/.test(header ?? ''),
          'commit subject must end with the vault issue ID, e.g. "chore(repo): do thing (RAPP-5)"',
        ],
        'no-attribution': ({ raw }) => [
          !/co-authored-by|generated with|generated by|🤖/i.test(raw ?? ''),
          'commit messages must carry no attribution trailers (Co-Authored-By, "Generated with ...", etc.)',
        ],
      },
    },
  ],
  rules: {
    'scope-empty': [2, 'never'],
    'subject-rapp-id': [2, 'always'],
    'no-attribution': [2, 'always'],
  },
};
