/**
 * The nationality picker's data (RAPP-21), generated by
 * `scripts/generate-country-names.mjs` from ICU and committed - never
 * hand-typed, so Ucraïna cannot drift into Ucrania-with-a-typo.
 *
 * The CANONICAL stored value is the Catalan name: `profiles.nationality` feeds
 * aggregate impact reporting and the seeded roster already uses Catalan names,
 * so every locale's picker DISPLAYS its own script but SAVES the same string.
 * An Arabic speaker picking سوريا and a Catalan speaker picking Síria produce
 * one reporting bucket, which is the entire point of a picker over free text.
 */

import countriesData from './countries.json';
import { SUPPORTED_LANGUAGES, type SupportedLanguage } from './languages';

export interface CountryOption {
  readonly code: string;
  /** What the player sees: the name in her own language. */
  readonly label: string;
  /** What gets stored: the Catalan name, identical from every locale. */
  readonly canonical: string;
}

interface CountryEntry {
  readonly code: string;
  readonly names: Record<SupportedLanguage, string>;
}

const COUNTRIES = countriesData as readonly CountryEntry[];
const COMBINING_MARKS = /[\u0300-\u036f]/g;

/**
 * The roster's own nationalities, pinned above the search so the answer most
 * players need is one tap, not one spelling.
 */
export const COMMON_COUNTRY_CODES: readonly string[] = ['SY', 'UA', 'AF', 'MA', 'VE', 'ES'];

/** Accent- and case-insensitive, so "siria" finds "Síria" and "سوريا" alike. */
function normalizeForSearch(value: string): string {
  return value.toLowerCase().normalize('NFD').replace(COMBINING_MARKS, '');
}

const NORMALIZED_SEARCH_TEXT_BY_CODE = new Map(
  COUNTRIES.map((entry) => [
    entry.code,
    Object.values(entry.names).map(normalizeForSearch).join('\n'),
  ]),
);

const COUNTRY_COLLATOR_BY_LOCALE = new Map(
  SUPPORTED_LANGUAGES.map((locale) => [locale, new Intl.Collator(locale)]),
);
const COUNTRY_OPTIONS_BY_LOCALE = new Map<SupportedLanguage, readonly CountryOption[]>();

export function getCountryOptions(locale: SupportedLanguage): readonly CountryOption[] {
  const cached = COUNTRY_OPTIONS_BY_LOCALE.get(locale);
  if (cached !== undefined) return cached;

  const collator = COUNTRY_COLLATOR_BY_LOCALE.get(locale);
  if (collator === undefined) return [];

  const options = COUNTRIES.map((entry) => ({
    code: entry.code,
    label: entry.names[locale],
    canonical: entry.names.ca,
  })).sort((a, b) => collator.compare(a.label, b.label));
  COUNTRY_OPTIONS_BY_LOCALE.set(locale, options);
  return options;
}

/**
 * Filters across EVERY language's name, not just the display locale: a player
 * often knows her country's Latin spelling from documents even when the app is
 * in Arabic, and vice versa.
 */
export function searchCountries(
  options: readonly CountryOption[],
  query: string,
): readonly CountryOption[] {
  const needle = normalizeForSearch(query.trim());
  if (needle === '') return options;
  return options.filter((option) =>
    NORMALIZED_SEARCH_TEXT_BY_CODE.get(option.code)?.includes(needle),
  );
}

/** The localized label for an already-stored canonical value, for re-display. */
export function countryLabelForCanonical(
  canonical: string,
  locale: SupportedLanguage,
): string | null {
  const entry = COUNTRIES.find((candidate) => candidate.names.ca === canonical);
  return entry === undefined ? null : entry.names[locale];
}
