// Generated by scripts/generate-push-edge-catalog.ts from the official i18n catalogs.
// Do not edit this file directly.

// prettier-ignore
export const PUSH_NOTIFICATION_FALLBACK_BODIES = {
  "ca": {
    "announcementFallbackBody": "Toca per llegir l'avís.",
    "eventFallbackBody": "Toca per veure l'activitat.",
    "messageTitle": "Nou missatge de l’equip",
    "messageBody": "Obre Ramassà per llegir-lo.",
    "forumFlagTitle": "Nou avís al fòrum",
    "forumFlagBody": "Obre la cua de moderació per revisar-lo.",
    "referralUpdateTitle": "Nova actualització d’una derivació",
    "referralUpdateBody": "Obre la fitxa de la participant per revisar-la.",
    "mentoringUpdateTitle": "Actualització de la teva cita privada",
    "mentoringUpdateBody": "Obre Ramassà per veure el dia i l’hora."
  },
  "es": {
    "announcementFallbackBody": "Toca para leer el aviso.",
    "eventFallbackBody": "Toca para ver la actividad.",
    "messageTitle": "Nuevo mensaje del equipo",
    "messageBody": "Abre Ramassà para leerlo.",
    "forumFlagTitle": "Nuevo aviso en el foro",
    "forumFlagBody": "Abre la cola de moderación para revisarlo.",
    "referralUpdateTitle": "Nueva actualización de una derivación",
    "referralUpdateBody": "Abre la ficha de la participante para revisarla.",
    "mentoringUpdateTitle": "Actualización de tu cita privada",
    "mentoringUpdateBody": "Abre Ramassà para ver el día y la hora."
  },
  "en": {
    "announcementFallbackBody": "Tap to read the notice.",
    "eventFallbackBody": "Tap to view the activity.",
    "messageTitle": "New message from the team",
    "messageBody": "Open Ramassà to read it.",
    "forumFlagTitle": "New forum report",
    "forumFlagBody": "Open the moderation queue to review it.",
    "referralUpdateTitle": "New referral update",
    "referralUpdateBody": "Open the participant record to review it.",
    "mentoringUpdateTitle": "Update to your private appointment",
    "mentoringUpdateBody": "Open Ramassà to see the date and time."
  },
  "ar": {
    "announcementFallbackBody": "اضغطي لقراءة الإشعار.",
    "eventFallbackBody": "اضغطي لعرض النشاط.",
    "messageTitle": "رسالة جديدة من الفريق",
    "messageBody": "افتحي Ramassà لقراءتها.",
    "forumFlagTitle": "بلاغ جديد في المنتدى",
    "forumFlagBody": "افتحي قائمة الإشراف لمراجعته.",
    "referralUpdateTitle": "تحديث جديد لإحالة",
    "referralUpdateBody": "افتحي سجل المشاركة لمراجعته.",
    "mentoringUpdateTitle": "تحديث لموعدك الخاص",
    "mentoringUpdateBody": "افتحي Ramassà لرؤية اليوم والوقت."
  },
  "fa": {
    "announcementFallbackBody": "برای خواندن اطلاعیه ضربه بزنید.",
    "eventFallbackBody": "برای دیدن برنامه ضربه بزنید.",
    "messageTitle": "پیام جدید از تیم",
    "messageBody": "Ramassà را باز کنید تا آن را بخوانید.",
    "forumFlagTitle": "گزارش جدید در انجمن",
    "forumFlagBody": "صف نظارت را برای بررسی باز کنید.",
    "referralUpdateTitle": "به‌روزرسانی جدید ارجاع",
    "referralUpdateBody": "پرونده شرکت‌کننده را برای بررسی باز کنید.",
    "mentoringUpdateTitle": "به‌روزرسانی قرار خصوصی شما",
    "mentoringUpdateBody": "Ramassà را باز کنید تا روز و ساعت را ببینید."
  }
} as const;

export type PushCatalogLanguage = keyof typeof PUSH_NOTIFICATION_FALLBACK_BODIES;
