// Generated by scripts/generate-push-edge-catalog.ts from the official i18n catalogs.
// Do not edit this file directly.

// prettier-ignore
export const PUSH_NOTIFICATION_FALLBACK_BODIES = {
  "ca": {
    "announcementFallbackBody": "Toca per llegir l'avís.",
    "eventFallbackBody": "Toca per veure l'activitat."
  },
  "es": {
    "announcementFallbackBody": "Toca para leer el aviso.",
    "eventFallbackBody": "Toca para ver la actividad."
  },
  "en": {
    "announcementFallbackBody": "Tap to read the notice.",
    "eventFallbackBody": "Tap to view the activity."
  },
  "ar": {
    "announcementFallbackBody": "اضغطي لقراءة الإشعار.",
    "eventFallbackBody": "اضغطي لعرض النشاط."
  },
  "fa": {
    "announcementFallbackBody": "برای خواندن اطلاعیه ضربه بزنید.",
    "eventFallbackBody": "برای دیدن برنامه ضربه بزنید."
  }
} as const;

export type PushCatalogLanguage = keyof typeof PUSH_NOTIFICATION_FALLBACK_BODIES;
