import { readFile } from 'node:fs/promises';
import { describe, expect, test } from 'bun:test';

const readSource = (path: string) => readFile(path, 'utf8');

describe('accessibility CI local service contract', () => {
  test('the browser gate consumes the public key generated by its local Supabase runtime', async () => {
    const [workflow, playwrightConfig, session] = await Promise.all([
      readSource('.github/workflows/ci.yml'),
      readSource('playwright.config.ts'),
      readSource('scripts/qa-web/session.ts'),
    ]);

    expect(workflow).toContain('EXPO_PUBLIC_SUPABASE_ANON_KEY');
    expect(workflow).toContain('supabase@2.90.0 status -o env');
    expect(workflow.match(/supabase@2\.90\.0/g)).toHaveLength(3);
    expect(playwrightConfig).toContain('process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY');
    expect(session).toContain('process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY');
  });
});
