import ar from '../packages/shared/i18n/locales/ar/push.json';
import ca from '../packages/shared/i18n/locales/ca/push.json';
import en from '../packages/shared/i18n/locales/en/push.json';
import es from '../packages/shared/i18n/locales/es/push.json';
import fa from '../packages/shared/i18n/locales/fa/push.json';

const catalogs = { ca, es, en, ar, fa } as const;

export function renderPushEdgeCatalog(): string {
  const fallbackBodies = Object.fromEntries(
    Object.entries(catalogs).map(([language, catalog]) => [
      language,
      {
        announcementFallbackBody: catalog.announcementFallbackBody,
        eventFallbackBody: catalog.eventFallbackBody,
        messageTitle: catalog.messageTitle,
        messageBody: catalog.messageBody,
        forumFlagTitle: catalog.forumFlagTitle,
        forumFlagBody: catalog.forumFlagBody,
        referralUpdateTitle: catalog.referralUpdateTitle,
        referralUpdateBody: catalog.referralUpdateBody,
        mentoringUpdateTitle: catalog.mentoringUpdateTitle,
        mentoringUpdateBody: catalog.mentoringUpdateBody,
      },
    ]),
  );

  return `// Generated by scripts/generate-push-edge-catalog.ts from the official i18n catalogs.
// Do not edit this file directly.

// prettier-ignore
export const PUSH_NOTIFICATION_FALLBACK_BODIES = ${JSON.stringify(fallbackBodies, null, 2)} as const;

export type PushCatalogLanguage = keyof typeof PUSH_NOTIFICATION_FALLBACK_BODIES;
`;
}

if (import.meta.main) {
  const output = new URL(
    '../supabase/functions/_shared/push-catalog.generated.ts',
    import.meta.url,
  );
  await Bun.write(output, renderPushEdgeCatalog());
}
