-- Player-owned service interest desired state, staff notification evidence,
-- and participant timeline integration (RAPP-45).

alter table public.service_submission_notifications
  add column service_interest_id uuid
    references public.service_interests (id) on delete set null;

alter table public.service_submission_notifications
  drop constraint service_submission_notifications_kind_check;
alter table public.service_submission_notifications
  add constraint service_submission_notifications_kind_check
    check (kind in ('published_edit', 'service_interest'));
alter table public.service_submission_notifications
  add constraint service_submission_notifications_interest_source_check
    check (kind = 'service_interest' or service_interest_id is null);

create unique index service_submission_notifications_interest_idx
  on public.service_submission_notifications (service_interest_id)
  where service_interest_id is not null;

comment on table public.service_submission_notifications is
  'Durable staff work generated by entity edits to published services and participant service-interest signals.';
comment on column public.service_submission_notifications.service_interest_id is
  'The interest transition that created this notification. It becomes null if the participant removes the interest or is erased.';

create or replace function private.notify_service_interest()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.service_submission_notifications (
    org_id,
    service_id,
    kind,
    created_by,
    service_interest_id
  ) values (
    new.org_id,
    new.service_id,
    'service_interest',
    new.user_id,
    new.id
  );
  return new;
end;
$$;

revoke all on function private.notify_service_interest()
  from public, anon, authenticated;

create trigger service_interests_notify_staff
  after insert on public.service_interests
  for each row execute function private.notify_service_interest();

create or replace function public.set_service_interest(
  p_service_id uuid,
  p_interested boolean
)
returns boolean
language plpgsql
volatile
security invoker
set search_path = ''
as $$
begin
  if (select public.current_app_role()) is distinct from 'player' then
    raise insufficient_privilege using message =
      'Only a player can change her service interest.';
  end if;
  if p_service_id is null or p_interested is null then
    raise check_violation using message =
      'A service id and desired interest state are required.';
  end if;

  if p_interested then
    insert into public.service_interests (service_id)
    values (p_service_id)
    on conflict on constraint service_interests_service_user_unique do nothing;
    return true;
  end if;

  delete from public.service_interests
  where service_id = p_service_id
    and user_id = (select auth.uid());
  return false;
end;
$$;

comment on function public.set_service_interest is
  'Idempotently sets the signed-in player own desired interest state for one visible service.';

revoke all on function public.set_service_interest(uuid, boolean)
  from public, anon, authenticated;
grant execute on function public.set_service_interest(uuid, boolean)
  to authenticated;

create or replace function public.participant_activity(participant_id uuid)
returns table (
  id uuid,
  kind text,
  occurred_at timestamptz,
  title text,
  detail text
)
language sql
security invoker
set search_path = ''
stable
as $$
  select
    interest.id,
    'service_interest'::text as kind,
    interest.created_at as occurred_at,
    coalesce(service.title->>'ca', service.title->>'en', '') as title,
    nullif(
      concat_ws(
        ' · ',
        nullif(service.provider_name, ''),
        nullif(category.name->>'ca', '')
      ),
      ''
    ) as detail
  from public.service_interests as interest
  join public.services as service
    on service.org_id = interest.org_id
   and service.id = interest.service_id
  join public.service_categories as category
    on category.org_id = service.org_id
   and category.id = service.category_id
  where interest.user_id = $1
  order by interest.created_at desc, interest.id;
$$;

comment on function public.participant_activity is
  'Staff participant timeline. Service interests are current participant activity and remain constrained by each source table RLS.';
